#!/bin/sh

#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE Rental CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Billing CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE CardInfo CASCADE CONSTRAINTS;
DROP TABLE AddressInfo CASCADE CONSTRAINTS;
DROP TABLE Car CASCADE CONSTRAINTS;
DROP TABLE Insurance CASCADE CONSTRAINTS;
DROP TABLE Discounts CASCADE CONSTRAINTS;
DROP TABLE CarCategory CASCADE CONSTRAINTS;
DROP TABLE LocAddInfo CASCADE CONSTRAINTS;

exit;
EOF

